import { create } from 'zustand'

const useCaseStore = create((set, get) => ({
  stage: 'IDLE',
  setStage: (stage) => set({ stage }),
  language: 'English',
  setLanguage: (language) => set({ language }),
  caseId: null,
  setCaseId: (caseId) => set({ caseId }),
  userProblem: '',
  setUserProblem: (userProblem) => set({ userProblem }),
  classifyResult: null,
  setClassifyResult: (classifyResult) => set({ classifyResult }),
  triageConfirmed: false,
  setTriageConfirmed: (triageConfirmed) => set({ triageConfirmed }),
  formData: {},
  setFormData: (formData) => set({ formData }),
  departmentInfo: null,
  setDepartmentInfo: (departmentInfo) => set({ departmentInfo }),
  departmentConfirmed: false,
  setDepartmentConfirmed: (v) => set({ departmentConfirmed: v }),
  rtiPrediction: null,
  setRtiPrediction: (rtiPrediction) => set({ rtiPrediction }),
  rtiDraft: null,
  setRtiDraft: (rtiDraft) => set({ rtiDraft }),
  grievanceResult: null,
  setGrievanceResult: (grievanceResult) => set({ grievanceResult }),
  error: null,
  setError: (error) => set({ error }),
  isLoading: false,
  setIsLoading: (isLoading) => set({ isLoading }),

  reset: () =>
    set({
      stage: 'IDLE',
      caseId: null,
      userProblem: '',
      classifyResult: null,
      triageConfirmed: false,
      formData: {},
      departmentInfo: null,
      departmentConfirmed: false,
      rtiPrediction: null,
      rtiDraft: null,
      grievanceResult: null,
      error: null,
      isLoading: false,
    }),
}))

export default useCaseStore
